// <auto-generated />
namespace NHPL_HQ.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class rotaImagePost2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rotaImagePost2));
        
        string IMigrationMetadata.Id
        {
            get { return "202002271431303_rota Image Post2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
